[project]
name = "pubg"
version = "1.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.0.0",
    "pyinstaller>=6.17.0",
    "pynput>=1.8.1",
    "pystray>=0.19.5",
]
